Repository WildCodeSchool-2024-09/JS-RemoteFR-Vert-CrewCodeIle-CartoCodile-P2, pull requests merged in 2024-11, with the labels that each got.

#16 feat: pseudoform components with style and fonts
  client/package.json
  client/postcss.config.js
  client/public/fonts/Koulen-Regular.ttf
  client/public/fonts/NotoSans-Regular.ttf
  client/src/App.css
  client/src/App.tsx
  client/src/components/PseudoForm.tsx
  client/src/index.css
  client/src/main.tsx
  client/src/pages/Home.tsx
  client/tailwind.config.js
  package-lock.json
Labels: Must have

#19 Feature/s1/home/logo titre
  client/index.html
  client/public/images/logo_Cartocodile.webp
  client/src/App.tsx
  client/src/components/Footer.tsx
  client/src/components/Header.tsx
  client/src/components/LogoTitre.tsx
  client/src/components/MenuBurger.tsx
  client/tsconfig.json
Labels: Must have

#17 feat: create rules component with style
  client/src/App.css
  client/src/components/Rules.tsx
  client/src/pages/Home.tsx
Labels: Must have

#31 feat: about page with ClientCards
  client/src/assets/data/clientdata.json
  client/src/components/ClientCard.tsx
  client/src/lib/definitions.ts
  client/src/pages/About.tsx
Labels: Should have

#27 Feature/s2/game/qcm
  client/index.css
  client/public/images/indice (1).png
  client/src/components/Game.tsx
  client/src/components/lib/definitions.ts
  client/src/pages/Gamepage.tsx
  server/src/app.ts
  server/src/data/badcountries.json
  server/src/data/countries.json
Labels: Must have

#42 Feature/s3/game/style
  client/src/components/Game.tsx
Labels: Must have

#47 Feat/s4/game/qcm
  client/src/components/Game.tsx
Labels: Must have

#49 feat: add button style
  client/src/components/Game.tsx
Labels: Could have

#57 fix: paste the footer at the bottom of the page
  client/src/App.tsx
  client/src/components/Footer.tsx
Labels: Could have
